version: '3'
services:
  web:
    build: .
    #image: php:7.2-apache
    container_name: tobb_etu_bil520_apache_container
    ports:
      - "8082:80"
    volumes:
      - ./php:/var/www/html
    networks:
      - my-network

  mysql:
    image: mysql:latest
    container_name: tobb_etu_bil520_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: tobb_etu_bil520
      MYSQL_USER: bil520
      MYSQL_PASSWORD: bil520
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3307:3306"
    networks:
      - my-network
networks:
  my-network: